/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 92
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_var = 2,
  anon_sym_const = 3,
  anon_sym_EQ = 4,
  anon_sym_if = 5,
  anon_sym_else = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_COMMA = 11,
  anon_sym_STAR_STAR = 12,
  anon_sym_STAR = 13,
  anon_sym_SLASH = 14,
  anon_sym_PERCENT = 15,
  anon_sym_PLUS = 16,
  anon_sym_DASH = 17,
  anon_sym_string = 18,
  anon_sym_number = 19,
  anon_sym_bool = 20,
  sym_identifier = 21,
  sym_number = 22,
  anon_sym_DQUOTE = 23,
  aux_sym_string_literal_token1 = 24,
  anon_sym_true = 25,
  anon_sym_false = 26,
  sym_escape_sequence = 27,
  anon_sym_PERCENT_PERCENT = 28,
  anon_sym_PERCENTs = 29,
  anon_sym_PERCENTg = 30,
  sym_source_file = 31,
  sym__definition = 32,
  sym_variable_declaration = 33,
  sym_variable_assignment = 34,
  sym__statement = 35,
  sym_if_statement = 36,
  sym_condition = 37,
  sym_block = 38,
  sym__expression = 39,
  sym_function_call = 40,
  sym_binary_expression = 41,
  sym_unary_expression = 42,
  sym__type = 43,
  sym_string_literal = 44,
  sym_boolean = 45,
  sym_format_specifier = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_if_statement_repeat1 = 48,
  aux_sym_block_repeat1 = 49,
  aux_sym_function_call_repeat1 = 50,
  aux_sym_string_literal_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_var] = "var",
  [anon_sym_const] = "const",
  [anon_sym_EQ] = "=",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_string] = "string",
  [anon_sym_number] = "number",
  [anon_sym_bool] = "bool",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_PERCENT_PERCENT] = "%%",
  [anon_sym_PERCENTs] = "%s",
  [anon_sym_PERCENTg] = "%g",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_variable_declaration] = "variable_declaration",
  [sym_variable_assignment] = "variable_assignment",
  [sym__statement] = "_statement",
  [sym_if_statement] = "if_statement",
  [sym_condition] = "condition",
  [sym_block] = "block",
  [sym__expression] = "_expression",
  [sym_function_call] = "function_call",
  [sym_binary_expression] = "binary_expression",
  [sym_unary_expression] = "unary_expression",
  [sym__type] = "_type",
  [sym_string_literal] = "string_literal",
  [sym_boolean] = "boolean",
  [sym_format_specifier] = "format_specifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_if_statement_repeat1] = "if_statement_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_bool] = anon_sym_bool,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_PERCENT_PERCENT] = anon_sym_PERCENT_PERCENT,
  [anon_sym_PERCENTs] = anon_sym_PERCENTs,
  [anon_sym_PERCENTg] = anon_sym_PERCENTg,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_variable_assignment] = sym_variable_assignment,
  [sym__statement] = sym__statement,
  [sym_if_statement] = sym_if_statement,
  [sym_condition] = sym_condition,
  [sym_block] = sym_block,
  [sym__expression] = sym__expression,
  [sym_function_call] = sym_function_call,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym__type] = sym__type,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean] = sym_boolean,
  [sym_format_specifier] = sym_format_specifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_if_statement_repeat1] = aux_sym_if_statement_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTs] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTg] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_format_specifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 7,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 13,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 14,
  [29] = 29,
  [30] = 15,
  [31] = 3,
  [32] = 32,
  [33] = 19,
  [34] = 20,
  [35] = 21,
  [36] = 24,
  [37] = 27,
  [38] = 26,
  [39] = 39,
  [40] = 39,
  [41] = 32,
  [42] = 42,
  [43] = 6,
  [44] = 11,
  [45] = 9,
  [46] = 10,
  [47] = 12,
  [48] = 48,
  [49] = 8,
  [50] = 48,
  [51] = 5,
  [52] = 42,
  [53] = 53,
  [54] = 53,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 63,
  [66] = 61,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 60,
  [73] = 62,
  [74] = 67,
  [75] = 75,
  [76] = 76,
  [77] = 76,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 80,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 85,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 87,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(39);
      ADVANCE_MAP(
        '"', 84,
        '%', 59,
        '(', 50,
        ')', 51,
        '*', 56,
        '+', 60,
        ',', 54,
        '-', 61,
        '/', 57,
        '=', 45,
        '\\', 36,
        'b', 24,
        'c', 22,
        'e', 16,
        'f', 7,
        'i', 13,
        'n', 34,
        's', 33,
        't', 28,
        'v', 6,
        '{', 52,
        '}', 53,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(84);
      if (lookahead == '%') ADVANCE(3);
      if (lookahead == '/') ADVANCE(86);
      if (lookahead == '\\') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0) ADVANCE(85);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 84,
        '(', 50,
        ')', 51,
        '+', 60,
        '-', 61,
        '/', 4,
        'f', 66,
        't', 76,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(93);
      if (lookahead == 'g') ADVANCE(95);
      if (lookahead == 's') ADVANCE(94);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(40);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(90);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(46);
      END_STATE();
    case 14:
      if (lookahead == 'g') ADVANCE(62);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(64);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(8);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(63);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 36:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(92);
      END_STATE();
    case 37:
      if (eof) ADVANCE(39);
      ADVANCE_MAP(
        '%', 58,
        '(', 50,
        ')', 51,
        '*', 56,
        '+', 60,
        ',', 54,
        '-', 61,
        '/', 57,
        '=', 45,
        'c', 74,
        'i', 70,
        'v', 65,
        '{', 52,
        '}', 53,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 38:
      if (eof) ADVANCE(39);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'c') ADVANCE(74);
      if (lookahead == 'e') ADVANCE(72);
      if (lookahead == 'i') ADVANCE(70);
      if (lookahead == 'v') ADVANCE(65);
      if (lookahead == '{') ADVANCE(52);
      if (lookahead == '}') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_var);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_const);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(40);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '%') ADVANCE(93);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_number);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '/') ADVANCE(40);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '/') ADVANCE(86);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '%' &&
          lookahead != '\\') ADVANCE(85);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_PERCENT_PERCENT);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_PERCENTs);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_PERCENTg);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 37},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 37},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 37},
  [6] = {.lex_state = 37},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 37},
  [9] = {.lex_state = 37},
  [10] = {.lex_state = 37},
  [11] = {.lex_state = 37},
  [12] = {.lex_state = 37},
  [13] = {.lex_state = 37},
  [14] = {.lex_state = 37},
  [15] = {.lex_state = 37},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 37},
  [18] = {.lex_state = 37},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 37},
  [23] = {.lex_state = 37},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 37},
  [28] = {.lex_state = 37},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 37},
  [31] = {.lex_state = 37},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 37},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 37},
  [40] = {.lex_state = 37},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 37},
  [43] = {.lex_state = 37},
  [44] = {.lex_state = 37},
  [45] = {.lex_state = 37},
  [46] = {.lex_state = 37},
  [47] = {.lex_state = 37},
  [48] = {.lex_state = 37},
  [49] = {.lex_state = 37},
  [50] = {.lex_state = 37},
  [51] = {.lex_state = 37},
  [52] = {.lex_state = 37},
  [53] = {.lex_state = 37},
  [54] = {.lex_state = 37},
  [55] = {.lex_state = 38},
  [56] = {.lex_state = 38},
  [57] = {.lex_state = 38},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 38},
  [60] = {.lex_state = 38},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 38},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 37},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 37},
  [68] = {.lex_state = 37},
  [69] = {.lex_state = 37},
  [70] = {.lex_state = 37},
  [71] = {.lex_state = 37},
  [72] = {.lex_state = 37},
  [73] = {.lex_state = 37},
  [74] = {.lex_state = 37},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 5},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_PERCENT_PERCENT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(88),
    [sym__definition] = STATE(17),
    [sym_variable_declaration] = STATE(17),
    [sym_variable_assignment] = STATE(17),
    [sym_if_statement] = STATE(17),
    [sym_block] = STATE(17),
    [sym_function_call] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_var] = ACTIONS(7),
    [anon_sym_const] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    STATE(84), 1,
      sym_condition,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(70), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [35] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(31), 8,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [60] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    STATE(83), 1,
      sym_condition,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(70), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [95] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(35), 8,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [117] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(39), 8,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [139] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      anon_sym_RPAREN,
    ACTIONS(43), 1,
      sym_number,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(54), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [171] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(47), 8,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [193] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_STAR_STAR,
    ACTIONS(49), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(51), 7,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [217] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_STAR_STAR,
    ACTIONS(49), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(51), 7,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [241] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(57), 8,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [263] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_STAR_STAR,
    ACTIONS(61), 1,
      anon_sym_PERCENT,
    ACTIONS(59), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(49), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
    ACTIONS(51), 6,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
  [291] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(65), 8,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [313] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(69), 8,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [335] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(73), 8,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [357] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    ACTIONS(77), 1,
      sym_number,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(53), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [389] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 2,
      anon_sym_var,
      anon_sym_const,
    STATE(18), 7,
      sym__definition,
      sym_variable_declaration,
      sym_variable_assignment,
      sym_if_statement,
      sym_block,
      sym_function_call,
      aux_sym_source_file_repeat1,
  [418] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 1,
      anon_sym_if,
    ACTIONS(89), 1,
      anon_sym_LBRACE,
    ACTIONS(92), 1,
      sym_identifier,
    ACTIONS(83), 2,
      anon_sym_var,
      anon_sym_const,
    STATE(18), 7,
      sym__definition,
      sym_variable_declaration,
      sym_variable_assignment,
      sym_if_statement,
      sym_block,
      sym_function_call,
      aux_sym_source_file_repeat1,
  [447] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(95), 1,
      sym_number,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [476] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [505] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_number,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [534] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_if,
    ACTIONS(107), 1,
      anon_sym_LBRACE,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(101), 2,
      anon_sym_var,
      anon_sym_const,
    STATE(22), 7,
      sym_variable_declaration,
      sym_variable_assignment,
      sym__statement,
      sym_if_statement,
      sym_block,
      sym_function_call,
      aux_sym_block_repeat1,
  [563] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(65), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [584] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(119), 1,
      sym_number,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(123), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [613] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(125), 1,
      sym_number,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(69), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [642] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      sym_number,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(6), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [671] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(129), 2,
      anon_sym_var,
      anon_sym_const,
    STATE(40), 7,
      sym_variable_declaration,
      sym_variable_assignment,
      sym__statement,
      sym_if_statement,
      sym_block,
      sym_function_call,
      aux_sym_block_repeat1,
  [700] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(69), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [721] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(135), 1,
      sym_number,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(64), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [750] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(73), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [771] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(31), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [794] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(139), 1,
      sym_number,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(42), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [823] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(141), 1,
      sym_number,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(123), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(45), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [852] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(143), 1,
      sym_number,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(123), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [881] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(145), 1,
      sym_number,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(123), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(47), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [910] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(147), 1,
      sym_number,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [939] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    ACTIONS(129), 2,
      anon_sym_var,
      anon_sym_const,
    STATE(39), 7,
      sym_variable_declaration,
      sym_variable_assignment,
      sym__statement,
      sym_if_statement,
      sym_block,
      sym_function_call,
      aux_sym_block_repeat1,
  [968] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(151), 1,
      sym_number,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(123), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [997] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    ACTIONS(129), 2,
      anon_sym_var,
      anon_sym_const,
    STATE(22), 7,
      sym_variable_declaration,
      sym_variable_assignment,
      sym__statement,
      sym_if_statement,
      sym_block,
      sym_function_call,
      aux_sym_block_repeat1,
  [1026] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(155), 1,
      anon_sym_RBRACE,
    ACTIONS(129), 2,
      anon_sym_var,
      anon_sym_const,
    STATE(22), 7,
      sym_variable_declaration,
      sym_variable_assignment,
      sym__statement,
      sym_if_statement,
      sym_block,
      sym_function_call,
      aux_sym_block_repeat1,
  [1055] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(157), 1,
      sym_number,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(123), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 6,
      sym__expression,
      sym_function_call,
      sym_binary_expression,
      sym_unary_expression,
      sym_string_literal,
      sym_boolean,
  [1084] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_STAR_STAR,
    ACTIONS(61), 1,
      anon_sym_PERCENT,
    ACTIONS(59), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(161), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(159), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
  [1112] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(39), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1132] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(57), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1152] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR_STAR,
    ACTIONS(51), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(49), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [1174] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR_STAR,
    ACTIONS(51), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(49), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [1196] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR_STAR,
    ACTIONS(169), 1,
      anon_sym_PERCENT,
    ACTIONS(167), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(49), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
    ACTIONS(51), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1222] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_STAR_STAR,
    ACTIONS(61), 1,
      anon_sym_PERCENT,
    ACTIONS(59), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(173), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(171), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
  [1250] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(47), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1270] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR_STAR,
    ACTIONS(169), 1,
      anon_sym_PERCENT,
    ACTIONS(167), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(175), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(171), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
  [1298] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 6,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(35), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_STAR_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1318] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR_STAR,
    ACTIONS(169), 1,
      anon_sym_PERCENT,
    ACTIONS(161), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(167), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(175), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(159), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
  [1346] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_STAR_STAR,
    ACTIONS(61), 1,
      anon_sym_PERCENT,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(59), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1373] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_STAR_STAR,
    ACTIONS(61), 1,
      anon_sym_PERCENT,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(59), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1400] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_else,
    STATE(57), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(183), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(185), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
  [1421] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_else,
    STATE(55), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(189), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(191), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
  [1442] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_else,
    STATE(57), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(195), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(197), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
  [1463] = 5,
    ACTIONS(202), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_DQUOTE,
    ACTIONS(206), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
    STATE(58), 2,
      sym_format_specifier,
      aux_sym_string_literal_repeat1,
    ACTIONS(209), 3,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENTs,
      anon_sym_PERCENTg,
  [1483] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(214), 5,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
  [1499] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(218), 5,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
  [1515] = 5,
    ACTIONS(202), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_DQUOTE,
    ACTIONS(222), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
    STATE(58), 2,
      sym_format_specifier,
      aux_sym_string_literal_repeat1,
    ACTIONS(224), 3,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENTs,
      anon_sym_PERCENTg,
  [1535] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(228), 5,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
  [1551] = 5,
    ACTIONS(202), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_DQUOTE,
    ACTIONS(232), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
    STATE(61), 2,
      sym_format_specifier,
      aux_sym_string_literal_repeat1,
    ACTIONS(224), 3,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENTs,
      anon_sym_PERCENTg,
  [1571] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_STAR_STAR,
    ACTIONS(61), 1,
      anon_sym_PERCENT,
    ACTIONS(59), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(234), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1593] = 5,
    ACTIONS(202), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_DQUOTE,
    ACTIONS(238), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
    STATE(66), 2,
      sym_format_specifier,
      aux_sym_string_literal_repeat1,
    ACTIONS(224), 3,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENTs,
      anon_sym_PERCENTg,
  [1613] = 5,
    ACTIONS(202), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_DQUOTE,
    ACTIONS(222), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
    STATE(58), 2,
      sym_format_specifier,
      aux_sym_string_literal_repeat1,
    ACTIONS(224), 3,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENTs,
      anon_sym_PERCENTg,
  [1633] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_EQ,
    ACTIONS(242), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(244), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
  [1650] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(250), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
  [1665] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_STAR_STAR,
    ACTIONS(61), 1,
      anon_sym_PERCENT,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    ACTIONS(59), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1686] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_STAR_STAR,
    ACTIONS(61), 1,
      anon_sym_PERCENT,
    ACTIONS(254), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1707] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(258), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
  [1722] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(218), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
  [1737] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(228), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
  [1752] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_EQ,
    ACTIONS(242), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(244), 4,
      anon_sym_var,
      anon_sym_const,
      anon_sym_if,
      sym_identifier,
  [1769] = 2,
    ACTIONS(202), 1,
      sym_comment,
    ACTIONS(262), 6,
      anon_sym_DQUOTE,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
      anon_sym_PERCENT_PERCENT,
      anon_sym_PERCENTs,
      anon_sym_PERCENTg,
  [1781] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(67), 1,
      sym__type,
    ACTIONS(264), 3,
      anon_sym_string,
      anon_sym_number,
      anon_sym_bool,
  [1793] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(74), 1,
      sym__type,
    ACTIONS(266), 3,
      anon_sym_string,
      anon_sym_number,
      anon_sym_bool,
  [1805] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(268), 1,
      anon_sym_if,
    STATE(71), 1,
      sym_block,
  [1818] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(268), 1,
      anon_sym_if,
    STATE(68), 1,
      sym_block,
  [1831] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_function_call_repeat1,
  [1844] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_function_call_repeat1,
  [1857] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    STATE(82), 1,
      aux_sym_function_call_repeat1,
  [1870] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      sym_block,
  [1880] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_LBRACE,
    STATE(56), 1,
      sym_block,
  [1890] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    ACTIONS(279), 1,
      anon_sym_EQ,
  [1900] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    ACTIONS(281), 1,
      anon_sym_EQ,
  [1910] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym_identifier,
  [1917] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      ts_builtin_sym_end,
  [1924] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_if,
  [1931] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_LBRACE,
  [1938] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 95,
  [SMALL_STATE(6)] = 117,
  [SMALL_STATE(7)] = 139,
  [SMALL_STATE(8)] = 171,
  [SMALL_STATE(9)] = 193,
  [SMALL_STATE(10)] = 217,
  [SMALL_STATE(11)] = 241,
  [SMALL_STATE(12)] = 263,
  [SMALL_STATE(13)] = 291,
  [SMALL_STATE(14)] = 313,
  [SMALL_STATE(15)] = 335,
  [SMALL_STATE(16)] = 357,
  [SMALL_STATE(17)] = 389,
  [SMALL_STATE(18)] = 418,
  [SMALL_STATE(19)] = 447,
  [SMALL_STATE(20)] = 476,
  [SMALL_STATE(21)] = 505,
  [SMALL_STATE(22)] = 534,
  [SMALL_STATE(23)] = 563,
  [SMALL_STATE(24)] = 584,
  [SMALL_STATE(25)] = 613,
  [SMALL_STATE(26)] = 642,
  [SMALL_STATE(27)] = 671,
  [SMALL_STATE(28)] = 700,
  [SMALL_STATE(29)] = 721,
  [SMALL_STATE(30)] = 750,
  [SMALL_STATE(31)] = 771,
  [SMALL_STATE(32)] = 794,
  [SMALL_STATE(33)] = 823,
  [SMALL_STATE(34)] = 852,
  [SMALL_STATE(35)] = 881,
  [SMALL_STATE(36)] = 910,
  [SMALL_STATE(37)] = 939,
  [SMALL_STATE(38)] = 968,
  [SMALL_STATE(39)] = 997,
  [SMALL_STATE(40)] = 1026,
  [SMALL_STATE(41)] = 1055,
  [SMALL_STATE(42)] = 1084,
  [SMALL_STATE(43)] = 1112,
  [SMALL_STATE(44)] = 1132,
  [SMALL_STATE(45)] = 1152,
  [SMALL_STATE(46)] = 1174,
  [SMALL_STATE(47)] = 1196,
  [SMALL_STATE(48)] = 1222,
  [SMALL_STATE(49)] = 1250,
  [SMALL_STATE(50)] = 1270,
  [SMALL_STATE(51)] = 1298,
  [SMALL_STATE(52)] = 1318,
  [SMALL_STATE(53)] = 1346,
  [SMALL_STATE(54)] = 1373,
  [SMALL_STATE(55)] = 1400,
  [SMALL_STATE(56)] = 1421,
  [SMALL_STATE(57)] = 1442,
  [SMALL_STATE(58)] = 1463,
  [SMALL_STATE(59)] = 1483,
  [SMALL_STATE(60)] = 1499,
  [SMALL_STATE(61)] = 1515,
  [SMALL_STATE(62)] = 1535,
  [SMALL_STATE(63)] = 1551,
  [SMALL_STATE(64)] = 1571,
  [SMALL_STATE(65)] = 1593,
  [SMALL_STATE(66)] = 1613,
  [SMALL_STATE(67)] = 1633,
  [SMALL_STATE(68)] = 1650,
  [SMALL_STATE(69)] = 1665,
  [SMALL_STATE(70)] = 1686,
  [SMALL_STATE(71)] = 1707,
  [SMALL_STATE(72)] = 1722,
  [SMALL_STATE(73)] = 1737,
  [SMALL_STATE(74)] = 1752,
  [SMALL_STATE(75)] = 1769,
  [SMALL_STATE(76)] = 1781,
  [SMALL_STATE(77)] = 1793,
  [SMALL_STATE(78)] = 1805,
  [SMALL_STATE(79)] = 1818,
  [SMALL_STATE(80)] = 1831,
  [SMALL_STATE(81)] = 1844,
  [SMALL_STATE(82)] = 1857,
  [SMALL_STATE(83)] = 1870,
  [SMALL_STATE(84)] = 1880,
  [SMALL_STATE(85)] = 1890,
  [SMALL_STATE(86)] = 1900,
  [SMALL_STATE(87)] = 1910,
  [SMALL_STATE(88)] = 1917,
  [SMALL_STATE(89)] = 1924,
  [SMALL_STATE(90)] = 1931,
  [SMALL_STATE(91)] = 1938,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_assignment, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_assignment, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 4, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2, 0, 0),
  [199] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [206] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [209] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 4, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 4, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 6, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 6, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 1, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format_specifier, 1, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [285] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dlitescript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dlitescript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
